baseURL = "https://tomkedem.github.io/AI-Developer-World-Class-Series/"
title = "AI Developer World Class Series"
theme = "book"

defaultContentLanguage = "he"
defaultContentLanguageInSubdir = true

[languages]

  [languages.he]
    languageName = "עברית"
    languageCode = "he-il"
    weight = 1
    languageDirection = "rtl"

  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 2
    languageDirection = "ltr"


[params]
  BookSection = "books"
  BookToC = true
  BookSearch = true
