baseURL = "https://tomkedem.github.io/AI-Developer-World-Class-Series/"
languageCode = "he-il"
title = "AI Developer World Class Series"
theme = "book"
defaultContentLanguage = "he"

[languages]
  [languages.he]
    languageName = "עברית"
    languageCode = "he"
    languageDirection = "rtl"

[params]
  BookSection = "books"
  BookToC = true
  BookSearch = true
